name: build 

on: 
  push: 
    branches: 
      - main

jobs:
  test:
    name: runs all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Installs libraries
        run: npm install

      - name: Runs tests
        run: npm run coverage


  